AllCops:
  Exclude:
    - 'demo.rb'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'player.rb'

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 110

Metrics/LineLength:
  Max: 100
