AllCops:
  Exclude:
    - 'demo.rb'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'blackjack_game.rb'
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Exclude:
    - 'blackjack_game.rb'
  Max: 110

Metrics/LineLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Exclude:
    - 'blackjack_game.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'blackjack_game.rb'

Style/Next:
  Exclude:
    - 'blackjack_game.rb'
